import{calculateRegular,calculateSickness,calculateDpp}from"./dovolena/calculations.js";import{LEGISLATION}from"./legislation/parameters.js";
const $=id=>document.getElementById(id),v=id=>$(id).value,n=id=>Number(v(id)),fmt=(x,d=4)=>new Intl.NumberFormat("cs-CZ",{maximumFractionDigits:d}).format(x);let mode="new";
function syncYear(){let y=n("year"),verified=LEGISLATION[y];$("law-status").textContent=verified?"Pravidla ověřena: "+verified.verifiedOn:"Rok legislativně neověřen";if(document.querySelector('input[name="leave-joined"]:checked').value==="no")$("leave-start").value=y+"-01-01";}
function joined(){let no=document.querySelector('input[name="leave-joined"]:checked').value==="no";$("leave-start").disabled=no;$("leave-start").value=no?n("year")+"-01-01":"";render();}
function calculate(){let year=n("year");if(!Number.isInteger(year)||year<2024||year>2100)throw Error("Neplatný rok.");if(mode==="new"){if(!v("new-start"))return null;return calculateRegular({year,start:v("new-start"),end:year+"-12-31",weeklyHours:n("new-hours"),leaveWeeks:n("new-weeks")});}if(mode==="leave"){if(!v("leave-start")||!v("leave-end"))return null;return calculateRegular({year,start:v("leave-start"),end:v("leave-end"),weeklyHours:n("leave-hours"),leaveWeeks:n("leave-weeks")});}if(mode==="sick"){if(!v("sick-from")||!v("sick-to"))return null;return calculateSickness({year,start:v("sick-start"),end:v("sick-end"),sicknessFrom:v("sick-from"),sicknessTo:v("sick-to"),weeklyHours:n("sick-hours"),leaveWeeks:n("sick-weeks"),workAccident:$("sick-accident").checked});}if(!v("dpp-start")||!v("dpp-end")||v("dpp-hours")==="")return null;return calculateDpp({year,start:v("dpp-start"),end:v("dpp-end"),creditedHours:n("dpp-hours"),leaveWeeks:n("dpp-weeks")});}
const row=(a,b)=>'<tr><td>'+a+'</td><td>'+b+'</td></tr>', esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function render(){syncYear();let r;try{r=calculate();}catch(e){$("result").innerHTML='<div class="warning" role="alert">'+esc(e.message)+'</div>';return;}if(!r){$("result").innerHTML='<div class="empty-state"><h2>Výsledek výpočtu</h2><p>Vyplňte vstupní údaje a zobrazíme počet týdnů, hodiny a postup výpočtu.</p></div>';return;}
let html='<p class="eyebrow">VÝSLEDEK VÝPOČTU</p><div class="results-grid"><div class="result-number"><strong>'+fmt(r.leaveWeeks,6)+'</strong><span>týdne dovolené</span></div><div class="result-number"><strong>'+fmt(r.hours)+' h</strong><span>hodin dovolené</span></div></div><h3>Postup výpočtu</h3><table class="calc-table">'+row("Celé započtené týdenní doby",r.fullMultiples+" z 52")+row("Týdenní pracovní doba",fmt(r.weeklyHours)+" h")+row("Výměra dovolené",fmt(r.annualLeaveWeeks)+" týdny")+'</table><h3>Nárok v týdnech</h3><div class="equation">'+(r.qualifies?r.fullMultiples+" / 52 × "+fmt(r.annualLeaveWeeks)+" = "+fmt(r.leaveWeeks,6)+" týdne":"Nárok = 0 týdnů")+'</div><h3>Nárok v hodinách</h3><div class="equation">'+(r.qualifies?r.fullMultiples+" / 52 × "+fmt(r.weeklyHours)+" × "+fmt(r.annualLeaveWeeks)+" = "+fmt(r.rawHours,6)+" h → "+fmt(r.hours)+" h":"Nárok = 0 h")+'</div>';
if(mode==="sick"){html+='<h3>Rozpis nemoci (§ 216)</h3><table class="calc-table">'+row("Mimo nemoc",fmt(r.outsideMultiples)+" týdenních dob")+row("Nemoc celkem",fmt(r.absentMultiples)+" týdenních dob")+row("Uznaná nemoc",fmt(r.recognizedMultiples)+" týdenních dob")+row("Neuznaná nemoc",fmt(r.notRecognizedMultiples)+" týdenních dob")+row("12 týdenních dob mimo nemoc",r.outsideCondition?"Splněno":"Nesplněno")+row("Nárok bez nemoci",fmt(r.baseline.leaveWeeks,6)+" týdne / "+r.baseline.hours+" h")+'</table><p class="summary">Snížení nároku: '+fmt(r.differenceWeeks,6)+' týdne / '+r.differenceHours+' h</p>';}
if(mode==="dpp")html+='<h3>Podmínky DPP</h3><table class="calc-table">'+row("Trvání v roce",r.contractDays+" dnů")+row("28 dnů",r.eligibleDays?"Splněno":"Nesplněno")+row("80 hodin",r.eligibleHours?"Splněno":"Nesplněno")+'</table>';
if(!r.qualifies)html+='<p class="warning">Nebyly splněny všechny podmínky pro vznik nároku.</p>';if(!LEGISLATION[n("year")])html+='<p class="warning">Pro tento rok nebyly parametry ověřeny; použit model roku 2026.</p>';
html+='<p class="note">Orientační výpočet: pravidelná pracovní doba po–pá. Skutečný rozvrh směn, další překážky a změny úvazku mohou výsledek změnit.</p>';$("result").innerHTML=html;}
document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{mode=tab.dataset.mode;document.querySelectorAll(".tab").forEach(t=>{t.classList.toggle("is-active",t===tab);t.setAttribute("aria-selected",String(t===tab));});document.querySelectorAll(".form-content").forEach(f=>f.hidden=f.dataset.form!==mode);render();}));
document.querySelectorAll("input").forEach(input=>input.addEventListener(input.name==="leave-joined"?"change":"input",input.name==="leave-joined"?joined:render));joined();render();
