import{paramsFor}from"../legislation/parameters.js";
const iso=y=>y+"-01-01",end=y=>y+"-12-31";
function checkDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||""))throw Error("Neplatné datum.");const d=new Date(s+"T12:00:00Z");if(isNaN(d)||d.toISOString().slice(0,10)!==s)throw Error("Neplatné datum.");return d;}
export function calendarDays(a,b){let x=checkDate(a),y=checkDate(b);return a>b?0:Math.round((y-x)/86400000)+1;}
export function weekdays(a,b){if(a>b)return 0;let n=0;for(let t=+checkDate(a),e=+checkDate(b);t<=e;t+=86400000){let d=new Date(t).getUTCDay();if(d&&d<6)n++}return n;}
function validate(y,h,w){if(!Number.isInteger(y)||y<2024||y>2100)throw Error("Neplatný rok.");if(!(h>0&&h<=80))throw Error("Úvazek musí být 0 až 80 hodin.");if(!(w>=4&&w<=20))throw Error("Výměra musí být 4 až 20 týdnů.");}
function period(a,b,y){checkDate(a);checkDate(b);if(a>b)throw Error("Začátek je později než konec.");let start=a>iso(y)?a:iso(y),finish=b<end(y)?b:end(y);if(start>finish)throw Error("Období nepatří do zvoleného roku.");return{start,end:finish};}
function entitlement(m,h,w,y,eligible=true){let ok=eligible&&m>=4,raw=ok?m*h*w/52:0;return{fullMultiples:m,denominator:52,weeklyHours:h,annualLeaveWeeks:w,leaveWeeks:ok?m*w/52:0,rawHours:raw,hours:ok?Math.ceil(raw-1e-9):0,qualifies:ok};}
export function calculateRegular({start,end,year=2026,weeklyHours=40,leaveWeeks=4}){validate(year,weeklyHours,leaveWeeks);let p=period(start,end,year),plannedWeekdays=weekdays(p.start,p.end),creditedHours=plannedWeekdays*weeklyHours/5;return{...entitlement(Math.floor(creditedHours/weeklyHours+1e-9),weeklyHours,leaveWeeks,year),plannedWeekdays,creditedHours,period:p,model:"Rovnoměrné směny po–pá"};}
export function calculateSickness({year=2026,start="",end="",sicknessFrom,sicknessTo,weeklyHours=40,leaveWeeks=4,workAccident=false}){validate(year,weeklyHours,leaveWeeks);let p=period(start||iso(year),end||endYear(year),year);checkDate(sicknessFrom);checkDate(sicknessTo);if(sicknessFrom>sicknessTo)throw Error("Obrácené období nemoci.");let a=sicknessFrom>p.start?sicknessFrom:p.start,b=sicknessTo<p.end?sicknessTo:p.end,absentDays=weekdays(a,b),totalDays=weekdays(p.start,p.end),absentHours=absentDays*weeklyHours/5,outsideHours=(totalDays-absentDays)*weeklyHours/5,cfg=paramsFor(year),outsideCondition=outsideHours>=12*weeklyHours,recognizedHours=workAccident?absentHours:outsideCondition?Math.min(absentHours,20*weeklyHours):0,creditedHours=outsideHours+recognizedHours,m=Math.floor(creditedHours/weeklyHours+1e-9),base=calculateRegular({start:p.start,end:p.end,year,weeklyHours,leaveWeeks}),r=entitlement(m,weeklyHours,leaveWeeks,year);return{...r,period:p,totalDays,absentDays,absentHours,absentMultiples:absentHours/weeklyHours,outsideHours,outsideMultiples:outsideHours/weeklyHours,outsideCondition,recognizedHours,recognizedMultiples:recognizedHours/weeklyHours,notRecognizedHours:absentHours-recognizedHours,notRecognizedMultiples:(absentHours-recognizedHours)/weeklyHours,creditedHours,differenceHours:Math.max(0,base.hours-r.hours),differenceWeeks:Math.max(0,base.leaveWeeks-r.leaveWeeks),baseline:base,workAccident};}
function endYear(y){return y+"-12-31"}
export function calculateDpp({year=2026,start,end,creditedHours,leaveWeeks=4}){validate(year,20,leaveWeeks);if(!Number.isFinite(creditedHours)||creditedHours<0)throw Error("Neplatné hodiny.");let p=period(start,end,year),contractDays=calendarDays(p.start,p.end),eligibleDays=contractDays>=28,eligibleHours=creditedHours>=80,m=Math.floor(creditedHours/20+1e-9);return{...entitlement(m,20,leaveWeeks,year,eligibleDays&&eligibleHours),contractDays,eligibleDays,eligibleHours,creditedHours,period:p};}
